from os import environ

GITHUB_ORG = environ["GITHUB_ORG"]
GITHUB_APP_ID = environ["GITHUB_APP_ID"]
GITHUB_APP_INSTALLATION_ID = environ["GITHUB_APP_INSTALLATION_ID"]
GITHUB_APP_PRIVATE_KEY = environ["GITHUB_APP_PRIVATE_KEY"]
STATE_BUCKET = environ["STATE_BUCKET"]

