#!/bin/zsh
TF_EXE=/usr/local/bin/terraform \
TF_INPUT=0 \
TF_IN_AUTOMATION=1 \
TF_CLI_ARGS_init=-plugin-dir=/Users/chris/source/repos/blueform/provisioner/app/providers \
TMP_DIR=/Users/chris/source/repos/blueform/provisioner/tmp \
PLAN_BUCKET=blufrm-user-plans \
GITHUB_ORG=project-blueform \
GITHUB_APP_ID=353187 \
GITHUB_APP_INSTALLATION_ID=39045450 \
GITHUB_APP_PRIVATE_KEY=$(cat ../.secrets/blueform-configurations.2023-06-27.private-key.pem) \
flask run --debug --port 5001

